version: '3.8'

services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    command: pnpm start:dev reservations

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    command: pnpm run start:dev auth

  mongo:
    image: mongo
